/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author user
 */
public class JFrmSlmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrmSlmPrincipal.class.getName());

    /**
     * Creates new form JFrmSlmPrincipal
     */
    public JFrmSlmPrincipal() {
        initComponents();
        setTitle("Sistema do IFMS");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuUsuario = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenuItem();
        jMenuMedicamento = new javax.swing.JMenuItem();
        jMenuVendedor = new javax.swing.JMenuItem();
        jMenuFornecedor = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenuItem();
        jMenuMovimentos = new javax.swing.JMenu();
        jMenuCompras = new javax.swing.JMenuItem();
        jMenuVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuCadastro.setMnemonic('c');
        jMenuCadastro.setText("Cadastro");

        jMenuUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/usuario.png"))); // NOI18N
        jMenuUsuario.setText("Usuario");
        jMenuUsuario.addActionListener(this::jMenuUsuarioActionPerformed);
        jMenuCadastro.add(jMenuUsuario);

        jMenuCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/cliente.png"))); // NOI18N
        jMenuCliente.setMnemonic('l');
        jMenuCliente.setText("Clientes");
        jMenuCliente.addActionListener(this::jMenuClienteActionPerformed);
        jMenuCadastro.add(jMenuCliente);

        jMenuMedicamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/produto.png"))); // NOI18N
        jMenuMedicamento.setMnemonic('m');
        jMenuMedicamento.setText("Medicamento");
        jMenuMedicamento.addActionListener(this::jMenuMedicamentoActionPerformed);
        jMenuCadastro.add(jMenuMedicamento);

        jMenuVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuVendedor.setMnemonic('v');
        jMenuVendedor.setText("Vendedor");
        jMenuVendedor.addActionListener(this::jMenuVendedorActionPerformed);
        jMenuCadastro.add(jMenuVendedor);

        jMenuFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuFornecedor.setMnemonic('f');
        jMenuFornecedor.setText("Fornecedor");
        jMenuFornecedor.addActionListener(this::jMenuFornecedorActionPerformed);
        jMenuCadastro.add(jMenuFornecedor);

        jMenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/exit.png"))); // NOI18N
        jMenuSair.setMnemonic('s');
        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(this::jMenuSairActionPerformed);
        jMenuCadastro.add(jMenuSair);

        jMenuBar1.add(jMenuCadastro);

        jMenuMovimentos.setText("Movimentos");

        jMenuCompras.setText("Compras");
        jMenuMovimentos.add(jMenuCompras);

        jMenuVendas.setText("Vendas");
        jMenuVendas.addActionListener(this::jMenuVendasActionPerformed);
        jMenuMovimentos.add(jMenuVendas);

        jMenuBar1.add(jMenuMovimentos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioActionPerformed
        // TODO add your handling code here:
        JDlgSlmUsuarios jDlgSlmUsuarios = new JDlgSlmUsuarios(null,true);
        jDlgSlmUsuarios.setVisible(true);
    }//GEN-LAST:event_jMenuUsuarioActionPerformed

    private void jMenuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuVendasActionPerformed

    private void jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteActionPerformed
        // TODO add your handling code here:
        JDlgSlmClientes jDlgSlmClientes = new JDlgSlmClientes(null,true);
        jDlgSlmClientes.setVisible(true);
    }//GEN-LAST:event_jMenuClienteActionPerformed

    private void jMenuMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMedicamentoActionPerformed
        // TODO add your handling code here:
        JDlgSlmMedicamento jDlgSlmMedicamento = new JDlgSlmMedicamento(null, true);
jDlgSlmMedicamento.setVisible(true);
    }//GEN-LAST:event_jMenuMedicamentoActionPerformed

    private void jMenuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVendedorActionPerformed
        // TODO add your handling code here:
          JDlgSlmVendedor jDlgSlmVendedor = new JDlgSlmVendedor(null, true);
jDlgSlmVendedor.setVisible(true);
    }//GEN-LAST:event_jMenuVendedorActionPerformed

    private void jMenuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFornecedorActionPerformed
        // TODO add your handling code here:
        JDlgSlmFornecedores jDlgSlmFornecedor = new JDlgSlmFornecedores(null, true);
jDlgSlmFornecedor.setVisible(true);
    }//GEN-LAST:event_jMenuFornecedorActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_jMenuSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrmSlmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuCliente;
    private javax.swing.JMenuItem jMenuCompras;
    private javax.swing.JMenuItem jMenuFornecedor;
    private javax.swing.JMenuItem jMenuMedicamento;
    private javax.swing.JMenu jMenuMovimentos;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JMenuItem jMenuUsuario;
    private javax.swing.JMenuItem jMenuVendas;
    private javax.swing.JMenuItem jMenuVendedor;
    // End of variables declaration//GEN-END:variables
}
